version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    groups:
      angular:
        patterns:
        - "@angular/*"
        update-types:
        - "minor"
        - "patch"
      angular-eslint:
        patterns:
        - "@angular-eslint/*"
        update-types:
        - "minor"
        - "patch"
      typescript-eslint:
        patterns:
        - "@typescript-eslint/*"
        update-types:
        - "minor"
        - "patch"
