name: CI pipeline

on: [ push, pull_request ]

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run frontend Unit tests
        run: npm run test

  e2e:
    name: End to End tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run End to End tests
        run: npm run e2e
      - name: Upload videos
        uses: actions/upload-artifact@v2
        with:
          name: e2e-videos
          path: cypress/videos

  build:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build UI
        run: npm run build
      - name: Upload bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: dist
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [unit, e2e, build]
    steps:
      - name: Unstash frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: bundle
          path: ./
      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ env.FTP_URL }}
          username: ${{ env.FTP_USER }}
          password: ${{ env.FTP_PASSWORD }}
          server-dir: ${{ env.FTP_SERVER_DIR }}

