name: CI pipeline

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run frontend Unit tests
        run: npm run test

  e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run End to End tests
        run: npm run e2e
      - name: Upload videos
        uses: actions/upload-artifact@v3
        with:
          name: e2e-videos
          path: cypress/videos

  build:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build UI
        run: npm run build
      - name: Stash bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: dist/upcoming-analyzer/

  publish:
    name: Publish Docker image
    if: github.ref == 'refs/heads/main'
    needs: [ lint, unit, e2e, build ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unstash bundle
        uses: actions/download-artifact@v3
        with:
          name: bundle
          path: docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push (latest)
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest
  
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    needs: [unit, e2e, build]
#    if: github.ref == 'refs/heads/main'
#    steps:
#      - name: Unstash bundle
#        uses: actions/download-artifact@v3
#        with:
#          name: bundle
#          path: ./
#      - name: Install lftp
#        run: sudo apt-get install lftp
#      - name: Pull .well-known
#        continue-on-error: true
#        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; mirror ${{ secrets.FTP_SERVER_DIR }}/.well-known ./; quit;" ${{ secrets.FTP_URL }}
#      - name: Push new bundle to remote
#        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; mirror --reverse ./ ${{ secrets.FTP_SERVER_DIR }}-${{ github.sha }} --verbose --parallel=10; quit;" ${{ secrets.FTP_URL }}
#      - name: Remove old backup
#        continue-on-error: true
#        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; rm -r ${{ secrets.FTP_SERVER_DIR }}.bak; quit;" ${{ secrets.FTP_URL }}
#      - name: Backup current bundle and deploy new bundle
#        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; mv ${{ secrets.FTP_SERVER_DIR }} ${{ secrets.FTP_SERVER_DIR }}.bak; mv ${{ secrets.FTP_SERVER_DIR }}-${{ github.sha }} ${{ secrets.FTP_SERVER_DIR }}; quit;" ${{ secrets.FTP_URL }}
