name: CI pipeline

on: [ push, pull_request ]

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run frontend Unit tests
        run: npm run test

  e2e:
    name: End to End tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run End to End tests
        run: npm run e2e
      - name: Upload videos
        uses: actions/upload-artifact@v2
        with:
          name: e2e-videos
          path: cypress/videos

  build:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build UI
        run: npm run build
      - name: Upload bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: dist/nextcloud-deck-upcoming-analyzer/
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [unit, e2e, build]
    steps:
      - name: Unstash frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: bundle
          path: ./
      - name: Install lftp
        run: sudo apt install lftp
      - name: Upload files
        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no;mirror ${{ secrets.FTP_SERVER_DIR }}/.well-known ./; mirror -R ./ ${{ secrets.FTP_SERVER_DIR }}-${{ env.GITHUB_SHA }}; rm -r ${{ secrets.FTP_SERVER_DIR }}.bak; mv ${{ secrets.FTP_SERVER_DIR }} ${{ secrets.FTP_SERVER_DIR }}.bak; mv ${{ secrets.FTP_SERVER_DIR }}-${{ env.GITHUB_SHA }} ${{ secrets.SERVER_DIR }}; quit;" ${{ secrets.FTP_URL }}
