name: CI pipeline

on: [ push, pull_request ]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run frontend Unit tests
        run: npm run test

  e2e-tests:
    name: End to End tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run End to End tests
        run: npm run e2e
#      - name: Upload videos
#        uses: actions/upload-artifact@v2
#        with:
#          name: e2e-videos
#          path: cypress/videos

  build:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build UI
        run: npm run build
      - name: Upload bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: dist
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, unit-tests]
    steps:
      - name: Unstash frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: bundle
          path: ./
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_URL }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}

